[client]
showErrorDetails = true
maxUploadSize = 200

[server]
maxUploadSize = 200
enableXsrfProtection = true

[logger]
level = "info"

[theme]
primaryColor = "#1E88E5"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"
